// src/components/SessionList.vue
<template>
  <div class="session-list">
    <template v-if="!serverStore.currentServer">
      <div
        v-for="sid in serverStore.servers"
        :key="sid"
        class="session"
        @click="selectServer(sid)"
      >
        <Avatar class="session-icon" type="server" :id="sid" />
        <span>{{ serverStore.getServerInfoById(sid)?.name || 'loading' }}</span>
      </div>
    </template>

    <div v-else>
      <div class="channel-title">
        <img id="back" alt="back" height="24" src="/images/icon/arrow_back.svg" width="24" @click="backToSessionList" />
        <span class="server-name" @click="toggleMenu($event)">{{ serverService.serverInfo?.name }}</span>
        <div class="context-menu" :class="{ show: isMenuOpen }">
          <div
            v-if="serverService.currentRolePermissions.includes(1)"
            class="menu-item"
            @click="handleMenuClick('settings')"
          >
            <span>服务器设置</span>
            <i class="icon-cog"></i>
          </div>
          <div class="menu-item" @click="handleMenuClick('invite')">
            <span>邀请用户</span>
            <i class="icon-user-plus"></i>
          </div>
          <div class="menu-divider"></div>
          <div class="menu-item danger" @click="handleMenuClick('leave')">
            <span>离开服务器</span>
            <i class="icon-exit"></i>
          </div>
        </div>
      </div>

      <div class="channel-list">
        <div v-for="group in serverService.serverInfo?.channels || []" :key="group.group_id || group.group_name" class="channel-group">
          <h3 class="channel-group-title">{{ group['group_name'] }}</h3>
          <ul class="channel-group-list">
            <template v-for="channel in group['channels']" :key="channel['channel_id']">
              <li class="channel" @click="toChat(channel['channel_id'], channel['channel_type'])">
                <img v-if="channel['channel_type'] === 'text'" src="/images/icon/text_chat.svg" class="icon" alt="" />
                <img v-if="channel['channel_type'] === 'voice'" src="/images/icon/voice_chat.svg" class="icon" alt="" />
                {{ channel['channel_name'] }}
              </li>
              <ul v-if="channel['channel_type'] === 'voice'" class="voice-user-list">
                <li v-for="member in membersFromChannels[channel['channel_id']] || []" :key="member.user_id + member.client_id" class="voice-user">
                  <Avatar class="user-avatar" :id="member.user_id" type="user" />
                  <span>{{ userStore.userInfoIndexById[member.user_id]?.data?.nickname || member.user_id }}</span>
                </li>
              </ul>
            </template>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <InviteDialog v-if="inviteDialog" :serverId="selectedServerId" @close="toggleInviteDialog" />
  <ServerSettingDialog v-if="serverSettingDialog" :serverId="selectedServerId" @close="toggleServerSettingDialog" />
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import { Subscription } from 'rxjs';
import { authState, layoutState, serverStore, uiState, userStore, voiceState } from '@/services/state';
import { requestService } from '@/services/request';
import { socketService } from '@/services/socket';
import { voiceChatService } from '@/services/voice-chat';
import { serverService } from '@/services/api/server';
import Avatar from './Avatar.vue';
import InviteDialog from './InviteDialog.vue';
import ServerSettingDialog from './ServerSettingDialog.vue';

const router = useRouter();
const selectedServerId = ref('');
const membersFromChannels = ref<Record<string, any[]>>({});
const subscriptions: Subscription[] = [];

const isMenuOpen = ref(false);
const inviteDialog = ref(false);
const serverSettingDialog = ref(false);

const toggleMenu = (event?: MouseEvent) => {
  event?.stopPropagation();
  isMenuOpen.value = !isMenuOpen.value;
};

const handleMenuClick = (action: string) => {
  isMenuOpen.value = false;
  if (action === 'invite') {
    toggleInviteDialog();
    return;
  }
  if (action === 'settings') {
    toggleServerSettingDialog();
    return;
  }
  if (action === 'leave') {
    leaveDialog();
  }
};

const toggleInviteDialog = () => {
  inviteDialog.value = !inviteDialog.value;
};

const toggleServerSettingDialog = () => {
  serverSettingDialog.value = !serverSettingDialog.value;
};

const leaveDialog = () => {
  if (!confirm('确认要离开该服务器吗？')) {
    return;
  }
  serverService.leaveServer(selectedServerId.value);
  serverStore.servers = serverStore.servers.filter((item) => item !== selectedServerId.value);
  serverStore.currentServer = '';
  router.push('/main/session');
};

const subscribeToMemberEvents = (serverId: string) => {
  const userJoinSub = socketService.getMessageSubject('server', 'user_join').subscribe(async (message) => {
    const user_ids = message['user_ids'];
    requestService.getUserInfo(user_ids).then();
    const memberRolesRecord = await serverService.getMembersRoles(serverId, user_ids);
    serverService.addUsers(user_ids, memberRolesRecord);
  });
  subscriptions.push(userJoinSub);

  const userLeaveSub = socketService.getMessageSubject('server', 'user_leave').subscribe((message) => {
    const user_id = message['user_id'];
    serverService.removeUser(user_id);
  });
  subscriptions.push(userLeaveSub);
};

const getMemberRoles = async (serverId: string): Promise<Record<string, string[]>> => {
  const memberIds = await serverService.getServerMemberIds(serverId);
  return serverService.getMembersRoles(serverId, memberIds);
};

const getServerRoles = async (serverId: string) => {
  return serverService.getServerRoles(serverId);
};

const selectServer = async (serverId: string) => {
  selectedServerId.value = serverId;
  serverStore.currentServer = serverId;
  await getServerChannels(serverId);
  await getMemberAndRoles(serverId);
  subscribeToMemberEvents(serverId);
};

const getServerChannels = async (serverId: string) => {
  const channelsData = await requestService.getServerChannels(serverId);
  const voiceChannelIds = channelsData.flatMap((group: { channels: any[] }) =>
    group.channels.filter((channel) => channel.channel_type === 'voice').map((channel) => channel.channel_id)
  );
  requestService.requestConnectToServerEventChannel(serverId).then(() => {
    requestService.getMembersFromVoiceChannels(voiceChannelIds).then((r) => {
      for (const [, members] of Object.entries(r)) {
        if (Array.isArray(members)) {
          requestService.getUserInfo(members.map((member: { user_id: string }) => member.user_id));
        }
      }
      membersFromChannels.value = r as Record<string, any[]>;
    });
  });
  serverService.serverInfo = serverStore.getServerInfoById(serverId);
};

const getMemberAndRoles = async (serverId: string) => {
  const [memberIds, memberRolesRecord, rolesRecord] = await Promise.all([
    serverService.getServerMemberIds(serverId),
    getMemberRoles(serverId),
    getServerRoles(serverId),
  ]);

  serverService.updateMemberData({
    memberIds,
    memberRolesRecord,
    rolesRecord,
  });

  serverService.currentRolePermissions = serverService.getUserPermissions(authState.clientUserId);
};

const backToSessionList = () => {
  requestService.requestDisconnectToServerEventChannel(selectedServerId.value).then();
  serverService.serverInfo = undefined;
  serverStore.currentServer = '';
  router.push('/main/session');
  isMenuOpen.value = false;
};

const toChat = async (channelId: any, channelType: any) => {
  if (channelType === 'text') {
    router.push({ path: '/main/session/chat', query: { channel_id: channelId } });
    if (uiState.isMobile) {
      layoutState.persistent = false;
      layoutState.secondary = false;
      layoutState.primary = true;
    } else {
      layoutState.primary = true;
    }
  } else if (channelType === 'voice') {
    const connected = await requestService.requestConnectToVoiceChannel(channelId);
    if (connected) {
      const members = membersFromChannels.value[channelId] || [];
      voiceChatService.initializeRecorder(channelId).then(() => {
        voiceState.voiceChatting = true;
        voiceState.voiceChannel = channelId;
        for (const member of members) {
          if (member.user_id === authState.clientUserId) {
            continue;
          }
          voiceChatService.join(member.user_id, member.client_id);
        }
      });
    }
  }
};

onMounted(() => {
  const serverEventSubject = socketService.getMessageSubject('server', 'server_event').subscribe((message) => {
    if (message['type'] === 'user_join_voice_channel') {
      const channelId = message['channel_id'];
      const userId = message['user_id'];
      const clientId = message['client_id'];
      const existing = membersFromChannels.value[channelId] || [];
      if (!existing.some((m: { user_id: string; client_id: string }) => m.user_id === userId && m.client_id === clientId)) {
        existing.push({ user_id: userId, client_id: clientId });
      }
      membersFromChannels.value[channelId] = existing;
      requestService.getUserInfo([userId]).then();
    }

    if (message['type'] === 'user_leave_voice_channel') {
      const channelId = message['channel_id'];
      const userId = message['user_id'];
      voiceChatService.leave(userId);
      if (membersFromChannels.value[channelId]) {
        membersFromChannels.value[channelId] = membersFromChannels.value[channelId].filter(
          (m: { user_id: string }) => m.user_id !== userId
        );
        if (membersFromChannels.value[channelId].length === 0) {
          delete membersFromChannels.value[channelId];
        }
      }
    }
  });
  subscriptions.push(serverEventSubject);
});

onBeforeUnmount(() => {
  subscriptions.forEach((subscription) => subscription.unsubscribe());
  serverStore.currentServer = '';
});
</script>

<style scoped>
@import url('./session-list.css');
</style>

// src-angular/app/components/session-list/session-list.component.ts
import {Component, EventEmitter, OnDestroy, OnInit, Output} from '@angular/core';
import {RequestService} from "../../services/request.service";
import {Router} from "@angular/router";
import {VoiceChatService} from "../../services/voice-chat.service";
import {CommonDataService} from "../../services/common-data.service";
import {NgForOf, NgIf, NgOptimizedImage} from "@angular/common";
import {SocketService} from "../../services/socket.service";
import {Subscription} from "rxjs";
import {FileService, FileType} from "../../services/file.service";
import {InviteDialogComponent} from "../invite-dialog/invite-dialog.component";
import {AvatarComponent} from "../avatar/avatar.component";
import {ServerSettingDialogComponent} from "../server-setting-dialog/server-setting-dialog.component";
import {Role, ServerService} from "../../services/api/server.service";

@Component({
  selector: 'app-session-list',
  standalone: true,
  imports: [
    NgIf,
    NgForOf,
    NgOptimizedImage,
    InviteDialogComponent,
    AvatarComponent,
    ServerSettingDialogComponent
  ],
  templateUrl: './session-list.component.html',
  styleUrl: './session-list.component.css'
})
export class SessionListComponent implements OnInit, OnDestroy {
  @Output() sessionSelected = new EventEmitter<{ sessionId: string | null, sessionType: string | null }>();
  protected serverId: string = "";
  protected membersFromChannels: any = {};  // 确保它是一个对象

  subscriptions: Subscription[] = [];

  constructor(protected serverService: ServerService,protected file: FileService, private socket: SocketService, protected commonDataService: CommonDataService, private requestService: RequestService, private router: Router, private voiceChatService: VoiceChatService) {
  }

  async ngOnInit(): Promise<void> {
    const serverEventSubject = this.socket.getMessageSubject("server", "server_event").subscribe(
      message => {
        if (message["type"] === "user_join_voice_channel") {
          const channelId = message["channel_id"];
          const userId = message["user_id"];
          const clientId = message["client_id"];
          // 如果该频道已存在成员列表，则添加；否则新建一个数组
          if (this.membersFromChannels[channelId]) {
            // 避免重复添加
            const exists = this.membersFromChannels[channelId].some(
              (m: { user_id: string; client_id: string }) =>
                m.user_id === userId && m.client_id === clientId
            );
            if (!exists) {
              this.membersFromChannels[channelId].push({user_id: userId, client_id: clientId});
            }
          } else {
            this.membersFromChannels[channelId] = [{"user_id": userId, "client_id": clientId}];
          }
          this.requestService.getUserInfo([userId]).then();
        }
        if (message["type"] === "user_leave_voice_channel") {
          const channelId = message["channel_id"];
          const userId = message["user_id"];
          this.voiceChatService.leave(userId)
          if (this.membersFromChannels[channelId]) {
            this.membersFromChannels[channelId] = this.membersFromChannels[channelId].filter(
              (m: { user_id: string; client_id: string }) =>
                !(m.user_id === userId)
            );
            if (this.membersFromChannels[channelId].length === 0) {
              delete this.membersFromChannels[channelId];
            }
          }
        }
      })
    this.subscriptions.push(serverEventSubject);
  }

  ngOnDestroy() {
    this.subscriptions.forEach(subscription => subscription.unsubscribe());

    //重置当前服务器选择
    this.commonDataService.currentServer = "";
  }

  private subscribeToMemberEvents(serverId: string) {
    // 用户加入事件
    const userJoinSub = this.socket
      .getMessageSubject("server", "user_join")
      .subscribe(async (message) => {
        const user_ids = message['user_ids'];

        // 获取用户信息
        this.requestService.getUserInfo(user_ids).then();

        // 获取新用户的角色
        const memberRolesRecord = await this.serverService.getMembersRoles(
          serverId,
          user_ids
        );

        // 更新 service 中的数据
        this.serverService.addUsers(user_ids, memberRolesRecord);
      });
    this.subscriptions.push(userJoinSub);

    // 用户离开事件
    const userLeaveSub = this.socket
      .getMessageSubject("server", "user_leave")
      .subscribe((message) => {
        const user_id = message['user_id'];
        this.serverService.removeUser(user_id);
      });
    this.subscriptions.push(userLeaveSub);
  }


  /**
   * 获取成员角色映射
   */
  private async getMemberRoles(serverId:string): Promise<Record<string, string[]>> {
    const memberIds = await this.serverService.getServerMemberIds(serverId);
    return this.serverService.getMembersRoles(serverId, memberIds);
  }

  /**
   * 获取服务器角色信息
   */
  private async getServerRoles(serverId:string): Promise<Record<string, Role>> {
    return this.serverService.getServerRoles(serverId);
  }

  public async selectServer(serverId:string){
    this.serverId = serverId;
    this.commonDataService.currentServer = serverId;
    await this.getServerChannels(serverId);
    await this.getMemberAndRoles(serverId);
    // 在这里订阅 WebSocket 事件
    this.subscribeToMemberEvents(serverId);

  }

  public async getServerChannels(serverId: string) {
    let channelsData = await this.requestService.getServerChannels(serverId)
    const voiceChannelIds = channelsData.flatMap((group: { channels: any[]; }) =>
      group.channels.filter(channel => channel.channel_type === "voice").map(channel => channel.channel_id)
    );
    this.requestService.requestConnectToServerEventChannel(serverId).then(r => {
      this.requestService.getMembersFromVoiceChannels(voiceChannelIds).then(r => {
        console.log(r)
        for (const [channelId, members] of Object.entries(r)) {
          // 确保 members 是一个数组
          if (Array.isArray(members)) {
            this.requestService.getUserInfo(
              members.map((member: { user_id: string; client_id: string }) => member.user_id)
            );
          } else {
            console.warn(`Invalid members data in channel ${channelId}:`, members);
          }
        }
        this.membersFromChannels = r;
      })
    })
    this.serverService.serverInfo = this.commonDataService.getServerInfoById(serverId)
  }



  async getMemberAndRoles(serverId: string) {
    const [memberIds, memberRolesRecord, rolesRecord] = await Promise.all([
      this.serverService.getServerMemberIds(serverId),
      this.getMemberRoles(serverId),
      this.getServerRoles(serverId)
    ]);

    // 统一更新
    this.serverService.updateMemberData({
      memberIds,
      memberRolesRecord,
      rolesRecord
    });

    this.serverService.currentRolePermissions =
      this.serverService.getUserPermissions(this.commonDataService.clientUserId);
  }

  backToSessionList() {
    this.requestService.requestDisconnectToServerEventChannel(this.serverId).then();
    this.serverService.serverInfo = undefined;
    this.commonDataService.currentServer = "";
    this.router.navigate(['/main/session']).then();
    this.isMenuOpen = false;
  }

  async toChat(channelId: any, channelType: any) {
    if (channelType == 'text') {
      this.router.navigate(['/main/session/chat'], {queryParams: {"channel_id": channelId}}).then();
      if (this.commonDataService.uiState.isMobile){
        this.commonDataService.uiState.persistent = false;
        this.commonDataService.uiState.secondary = false;
        this.commonDataService.uiState.primary = true;
      }else {
        this.commonDataService.uiState.primary = true;
      }
    } else if (channelType == 'voice') {
      const connected = await this.requestService.requestConnectToVoiceChannel(channelId);
      if (connected) {
        const members = this.membersFromChannels[channelId];
        console.log(members); // 当前频道的所有用户
        this.voiceChatService.initializeRecorder(channelId).then(() => {
          this.commonDataService.voiceChatting = true;
          this.commonDataService.voiceChannel = channelId;
          for (const member of members) {
            if (member.user_id == this.commonDataService.clientUserId){
              continue;
            }
            this.voiceChatService.join(member.user_id,member.client_id)
          }
        });
      }
    }
  }

  // 组件中添加
  isMenuOpen = false;

  toggleMenu(event: MouseEvent) {
    event.stopPropagation();
    this.isMenuOpen = !this.isMenuOpen;
  }

  handleMenuClick(action: string) {
    this.isMenuOpen = false;
    if (action == "invite"){
      this.toggleInviteDialog()
      return
    }
    if (action == "settings"){
      this.toggleServerSettingDialog()
      return;
    }
    if (action == "leave") {
      this.leaveDialog()
      return;
    }
    // 处理不同菜单操作
    console.log('Selected action:', action);
  }

  inviteDialog = false
  serverSettingDialog = false
  toggleInviteDialog() {
    this.inviteDialog = !this.inviteDialog;
  }
  toggleServerSettingDialog() {
    this.serverSettingDialog = !this.serverSettingDialog;
  }
  leaveDialog() {
    if (!confirm("确认要离开该服务器吗？")) {
      return;
    }
    this.serverService.leaveServer(this.serverId);
    this.commonDataService.servers = this.commonDataService.servers.filter(item => item != this.serverId);
    this.commonDataService.currentServer = "";
    this.router.navigate(['/main/session']).then();
  }
}

<div class="session-list">


  <ng-container *ngIf="!commonDataService.currentServer">
    <div (click)="selectServer(serverId)" *ngFor="let serverId of commonDataService['servers']" class="session">
      <app-avatar class="session-icon" type="server" [id]="serverId"></app-avatar>
      <span>{{ commonDataService.getServerInfoById(serverId)?.name || 'loading' }}</span>
    </div>
  </ng-container>



  <div *ngIf="commonDataService.currentServer">
    <div class="channel-title">
      <img id="back" (click)="backToSessionList()" alt="back" height="24" ngSrc="/images/icon/arrow_back.svg" width="24">
      <span class="server-name" (click)="toggleMenu($event)">{{ serverService.serverInfo['name'] }}</span>
      <!-- 菜单容器 -->
      <div class="context-menu" [class.show]="isMenuOpen">
        <div *ngIf="serverService.currentRolePermissions.includes(1)" class="menu-item" (click)="handleMenuClick('settings')">
          <span>服务器设置</span>
          <i class="icon-cog"></i>
        </div>
        <div class="menu-item" (click)="handleMenuClick('invite')">
          <span>邀请用户</span>
          <i class="icon-user-plus"></i>
        </div>
        <div class="menu-divider"></div>
        <div class="menu-item danger" (click)="handleMenuClick('leave')">
          <span>离开服务器</span>
          <i class="icon-exit"></i>
        </div>
      </div>
    </div>



    <div class="channel-list">
      <div *ngFor="let group of serverService.serverInfo['channels']" class="channel-group">
        <h3 class="channel-group-title">{{ group['group_name'] }}</h3>
        <ul class="channel-group-list">
          <ng-container *ngFor="let channel of group['channels']">
            <!-- 频道条目 -->
            <li (click)="toChat(channel['channel_id'], channel['channel_type'])" class="channel">
              <img *ngIf="channel['channel_type'] === 'text'" src="/images/icon/text_chat.svg" class="icon" alt="">
              <img *ngIf="channel['channel_type'] === 'voice'" src="/images/icon/voice_chat.svg" class="icon" alt="">
              {{ channel['channel_name'] }}
            </li>
            <!-- 如果是语音频道，则显示成员列表，放在频道下方 -->
            <ul *ngIf="channel['channel_type'] === 'voice'" class="voice-user-list">
              <li *ngFor="let member of membersFromChannels[channel['channel_id']]" class="voice-user">
                <app-avatar class="user-avatar" [id]="member.user_id" type="user"/>
                <span>{{ commonDataService.userInfoIndexById[member.user_id].data["nickname"]}}</span>
              </li>
            </ul>
          </ng-container>
        </ul>
      </div>
    </div>



  </div>
</div>


<app-invite-dialog [serverId]="serverId" *ngIf="inviteDialog" (close)="toggleInviteDialog()"/>
<app-server-setting-dialog  [serverId]="serverId" *ngIf="serverSettingDialog" (close)="toggleServerSettingDialog()"/>
