// src/app/pages/main/main.component.ts
import {AfterViewInit, Component, OnDestroy, OnInit} from '@angular/core';
import {Router, RouterOutlet} from "@angular/router";
import {NgClass, NgForOf, NgIf, NgOptimizedImage} from "@angular/common";
import {CommonDataService} from "../../services/common-data.service";
import {SocketService} from "../../services/socket.service";
import {Subscription} from "rxjs";
import {VoiceChatService} from "../../services/voice-chat.service";
import {RequestService} from "../../services/request.service";
import {ChatComponent} from "../chat/chat.component";
import {FileService, FileType} from "../../services/file.service";
import {AvatarComponent} from "../../components/avatar/avatar.component";

@Component({
  selector: 'app-main',
  standalone: true,
  imports: [
    RouterOutlet,
    NgOptimizedImage,
    NgForOf,
    NgIf,
    ChatComponent,
    NgClass,
    AvatarComponent
  ],
  templateUrl: './main.component.html',
  styleUrl: './main.component.css'
})
export class MainComponent implements OnInit, OnDestroy {
  subscriptions: Subscription[] = [];
  userAvatarId: string = "";

  ngOnDestroy() {
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }

  constructor(
    protected file: FileService,
    protected request: RequestService,
    private router: Router,
    private socketService: SocketService,
    protected commonData: CommonDataService,
    private voiceChatService: VoiceChatService) {
  }

  options = [
    {name: 'chat', icon: '/images/icon/chat_bubble.svg', height: 38, width: 38},
    // {name: 'groups', icon: '/images/icon/groups.svg', height: 38, width: 38},
    {name: 'channels', icon: '/images/icon/campaign.svg', height: 38, width: 38},
    {name: 'person', icon: '/images/icon/person.svg', height: 38, width: 38},
    {name: 'call', icon: '/images/icon/call.svg', height: 38, width: 38},
    {name: 'settings', icon: '/images/icon/settings.svg', height: 38, width: 38},
  ];

  selectedOption: string = 'chat';  // 记录当前选中的选项.

  // 处理选择操作，更新 selectedOption
  onSelect(option: any) {
    this.selectedOption = option.name;
    switch (option.name) {
      case 'channels':{
        this.router.navigate(['/main/channels']).then();
        break
      }
      case 'userInfo': {
        this.router.navigate(['/main/user-info']).then();
        break
      }
      case 'chat': {
        this.router.navigate(['/main/session']).then();
        break
      }
      case 'settings': {
        this.router.navigate(['/main/settings']).then();
        break
      }
      case 'person': {
        this.router.navigate(['/main/contacts']).then();
      }
    }
  }

  ngOnInit(): void {
    this.request.getUserInfo([this.commonData.clientUserId]).then(() => {
    })
    // 订阅各种服务器推送
    let newServerSubject=  this.socketService.getMessageSubject("server","new_server").subscribe(message => {
      let server_id = message['server_id'];
      this.commonData.servers.push(server_id);
      this.request.requestServerInfoByIds([server_id])
    })
    this.subscriptions.push(newServerSubject);
    let newFriendSubject=  this.socketService.getMessageSubject("user","new_friend").subscribe(message => {
      let user_id = message['user_id'];
      this.commonData.friends.push(user_id);
      this.request.getUserInfo([user_id]).then();
    })
    this.subscriptions.push(newFriendSubject);
  }

  toUserInfo(){
    this.router.navigate(['/main/user_info'],{queryParams: {"user_id": this.commonData.clientUserId}}).then();
  }


  protected readonly FileType = FileType;
}

<div class="container">
    <div class="sidebar">
        <div class="user-options">
          <img (click)="toUserInfo()" class="avatar" [src]="file.completedFiles[FileType.AVATAR][userAvatarId]?.url || '/images/avatar/default-avatar.png'">
            <ng-container *ngFor="let option of options">
                <img (click)="onSelect(option)"
                     [ngClass]="{'selected': selectedOption === option.name}"
                     [alt]="option.name"
                     class="icon"
                     [src]="option.icon"
                     [height]="option.height"
                     [width]="option.width">
            </ng-container>
        </div>
    </div>
    <div class="content">
        <router-outlet></router-outlet>
    </div>
</div>

// src/pages/main/Main.vue
<template>
  <div class="container">
    <div class="sidebar">
      <div class="user-options">
        <Avatar class="avatar" :id="authState.clientUserId" type="user" @click="toUserInfo" />
        <template v-for="option in options" :key="option.name">
          <img
            class="icon"
            :class="{ selected: selectedOption === option.name }"
            :alt="option.name"
            :src="option.icon"
            :height="option.height"
            :width="option.width"
            @click="onSelect(option)"
          />
        </template>
      </div>
    </div>
    <div class="content">
      <RouterView />
    </div>
  </div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { RouterView, useRouter } from 'vue-router';
import { Subscription } from 'rxjs';
import Avatar from '@/components/Avatar.vue';
import { authState, serverStore, userStore } from '@/services/state';
import { socketService } from '@/services/socket';
import { requestService } from '@/services/api/request';

const router = useRouter();
const subscriptions: Subscription[] = [];

const options = [
  { name: 'chat', icon: '/images/icon/chat_bubble.svg', height: 38, width: 38 },
  { name: 'channels', icon: '/images/icon/campaign.svg', height: 38, width: 38 },
  { name: 'person', icon: '/images/icon/person.svg', height: 38, width: 38 },
  { name: 'call', icon: '/images/icon/call.svg', height: 38, width: 38 },
  { name: 'settings', icon: '/images/icon/settings.svg', height: 38, width: 38 },
];

const selectedOption = ref('chat');

const onSelect = (option: any) => {
  selectedOption.value = option.name;
  switch (option.name) {
    case 'channels':
      router.push('/main/channels');
      break;
    case 'userInfo':
      router.push('/main/user_info');
      break;
    case 'chat':
      router.push('/main/session');
      break;
    case 'settings':
      router.push('/main/settings');
      break;
    case 'person':
      router.push('/main/contacts');
      break;
    default:
      break;
  }
};

onMounted(() => {
  requestService.getUserInfo([authState.clientUserId]).then();

  const newServerSubject = socketService.getMessageSubject('server', 'new_server').subscribe((message) => {
    const server_id = message['server_id'];
    serverStore.servers.push(server_id);
    requestService.requestServerInfoByIds([server_id]);
  });
  subscriptions.push(newServerSubject);

  const newFriendSubject = socketService.getMessageSubject('user', 'new_friend').subscribe((message) => {
    const user_id = message['user_id'];
    userStore.friends.push(user_id);
    requestService.getUserInfo([user_id]).then();
  });
  subscriptions.push(newFriendSubject);
});

onBeforeUnmount(() => {
  subscriptions.forEach((subscription) => subscription.unsubscribe());
});

const toUserInfo = () => {
  router.push({ path: '/main/user_info', query: { user_id: authState.clientUserId } });
  selectedOption.value = '';
};
</script>

<style scoped>
.container {
  height: 100%;
  width: 100%;
  display: flex;
  flex-direction: row;
}

.sidebar {
  display: flex;
}

.avatar {
  width: 48px;
}

.icon {
  margin-top: 1rem;
  background: var(--color-bg-sidebar);
  border-radius: 10px;
  padding: 5px;
}

.selected {
  background-color: var(--color-bg-sidebar-row-active);
  transform: scale(1.1);
}

.user-options {
  overflow-y: scroll;
  padding: 0.5rem;
  background-color: var(--color-primary-strong);
  display: flex;
  flex-direction: column;
}

.user-options::-webkit-scrollbar {
  display: none;
}

.content {
  background: var(--color-bg-main);
  flex: 1;
  display: flex;
}

.channel:hover {
  background-color: var(--color-warning-hover);
}
</style>
