// src/components/ChatImage.vue
<template>
  <img
    class="message-img"
    :src="`${networkConfig.httpPrefix}/chat/get_image?key=${image}`"
    :style="{ width: `${displayWidth}px`, height: `${displayHeight}px` }"
    alt=""
  />
</template>

<script setup lang="ts">
import { computed } from 'vue';
import { networkConfig } from '@/services/state';

const props = defineProps<{
  image: string;
  h: string;
  w: string;
}>();

const maxDisplayWidth = computed(() => Math.floor(window.innerWidth * 0.5));
const maxDisplayHeight = computed(() => Math.floor(window.innerHeight * 0.4));

const getScale = () => {
  const origW = Number(props.w);
  const origH = Number(props.h);
  if (!origW || !origH || origW <= 0 || origH <= 0) return 1;
  const scaleW = maxDisplayWidth.value / origW;
  const scaleH = maxDisplayHeight.value / origH;
  return Math.min(scaleW, scaleH, 1);
};

const displayWidth = computed(() => {
  const origW = Number(props.w);
  if (!origW || origW <= 0) return 200;
  const scale = getScale();
  return Math.floor(origW * scale);
});

const displayHeight = computed(() => {
  const origH = Number(props.h);
  if (!origH || origH <= 0) return 200;
  const scale = getScale();
  return Math.floor(origH * scale);
});
</script>

<style scoped>
.message-img {
  object-fit: contain;
  border-radius: 8px;
  display: block;
  width: 100%;
  height: 100%;
}
</style>

// src/app/components/chat-image/chat-image.component.ts
import {Component, Input} from '@angular/core';
import {NgIf} from "@angular/common";
import {CommonDataService} from "../../services/common-data.service";

@Component({
  selector: 'app-chat-image',
  standalone: true,
  imports: [NgIf],
  templateUrl: './chat-image.component.html',
  styleUrl: './chat-image.component.css'
})
export class ChatImageComponent {

  constructor(protected commonData: CommonDataService) {}

  @Input() image!: string;
  @Input() h!: string;
  @Input() w!: string;

  get maxDisplayWidth(): number {
    return Math.floor(window.innerWidth * 0.5);
  }

  get maxDisplayHeight(): number {
    return Math.floor(window.innerHeight * 0.4);
  }

  private getScale(): number {
    const origW = Number(this.w);
    const origH = Number(this.h);

    if (!origW || !origH || origW <= 0 || origH <= 0) return 1;

    const maxW = this.maxDisplayWidth;
    const maxH = this.maxDisplayHeight;

    // 计算缩放比例，取最小值确保不超出任何限制
    const scaleW = maxW / origW;
    const scaleH = maxH / origH;

    return Math.min(scaleW, scaleH, 1); // 永远不放大，最多1:1
  }

  get displayWidth(): number {
    const origW = Number(this.w);
    if (!origW || origW <= 0) return 200; // 默认值

    const scale = this.getScale();
    return Math.floor(origW * scale);
  }

  get displayHeight(): number {
    const origH = Number(this.h);
    if (!origH || origH <= 0) return 200; // 默认值

    const scale = this.getScale();
    return Math.floor(origH * scale);
  }
}


<!-- template -->
<img
  class="message-img"
  [src]="commonData.httpPrefix + '/chat/get_image?key=' + image"
  [style.width.px]="displayWidth"
  [style.height.px]="displayHeight"
  alt=""/>
