// src/components/DevConsole.vue
<template>
  <div class="dev-console">
    <div v-for="(log, index) in logs" :key="index">{{ log }}</div>
  </div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';

const logs = ref<string[]>([]);
let originalLog: (...args: any[]) => void;

onMounted(() => {
  originalLog = console.log;
  console.log = (...args: any[]) => {
    const message = args
      .map((arg) => (typeof arg === 'object' ? JSON.stringify(arg) : String(arg)))
      .join(' ');
    logs.value.push(message);
    if (logs.value.length > 1000) {
      logs.value.shift();
    }
    originalLog.apply(console, args);
  };
});

onBeforeUnmount(() => {
  if (originalLog) {
    console.log = originalLog;
  }
});
</script>

<style scoped>
.dev-console {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: rgba(0, 0, 0, 0.85);
  color: #0f0;
  font-family: monospace;
  font-size: 12px;
  overflow-y: auto;
  padding: 10px;
  z-index: 9999;
  pointer-events: none;
}
</style>

// src/app/components/dev-console/dev-console.component.ts
import {Component, OnInit} from '@angular/core';
import {NgForOf} from "@angular/common";

@Component({
  selector: 'app-dev-console',
  standalone: true,
  imports: [
    NgForOf
  ],
  templateUrl: './dev-console.component.html',
  styleUrl: './dev-console.component.css'
})
export class DevConsoleComponent implements OnInit{
  logs: string[] = [];

  ngOnInit(): void {
    const originalLog = console.log;

    console.log = (...args: any[]) => {
      const message = args.map(arg => typeof arg === 'object' ? JSON.stringify(arg) : String(arg)).join(' ');
      this.logs.push(message);
      if (this.logs.length > 1000) {
        this.logs.shift();
      }
      originalLog.apply(console, args);
    };
  }
}

<div class="dev-console">
  <div *ngFor="let log of logs">{{ log }}</div>
</div>
