// src/app/components/member-list/member-list.component.ts
import {Component, OnDestroy, OnInit} from '@angular/core';
import { AvatarComponent } from '../avatar/avatar.component';
import { NgForOf, NgIf } from '@angular/common';
import { CommonDataService } from '../../services/common-data.service';
import { ServerService, Role } from '../../services/api/server.service';
import {SocketService} from "../../services/socket.service";
import {RequestService} from "../../services/request.service";
import {Subscription} from "rxjs";

interface MemberGroup {
  roleName: string;
  userIds: string[];
}

@Component({
  selector: 'app-member-list',
  standalone: true,
  imports: [
    AvatarComponent,
    NgIf,
    NgForOf
  ],
  templateUrl: './member-list.component.html',
  styleUrl: './member-list.component.css'
})
export class MemberListComponent implements OnInit, OnDestroy {
  public membersByRole: MemberGroup[] = [];
  public subscriptions: Subscription[] = [];

  constructor(
    protected commonData: CommonDataService,
    protected serverService: ServerService,
    protected socketService: SocketService,
    protected request: RequestService
  ) {}

  async ngOnInit(): Promise<void> {
    if (!this.commonData.currentServer) {
      return;
    }

    // 订阅数据变化，自动更新显示
    const memberDataSub = this.serverService.memberData$.subscribe(data => {
      if (data) {
        this.loadAndGroupMembers(data);
      }
    });
    this.subscriptions.push(memberDataSub);
  }

  /**
   * 加载并分组成员数据
   */
  private loadAndGroupMembers(data: {
    memberIds: string[];
    memberRolesRecord: Record<string, string[]>;
    rolesRecord: Record<string, Role>;
  }): void {
    // 获取用户信息
    this.request.getUserInfo(data.memberIds).then();

    const roleMap = this.createRoleMap(data.rolesRecord);
    const memberGroups = this.groupMembersByHighestRole(
      data.memberIds,
      data.memberRolesRecord,
      roleMap
    );
    this.membersByRole = this.convertToTemplateFormat(memberGroups, roleMap);
  }

  /**
   * 创建角色ID到角色对象的映射
   */
  private createRoleMap(rolesRecord: Record<string, Role>): Map<string, Role> {
    const roleMap = new Map<string, Role>();

    Object.entries(rolesRecord).forEach(([roleId, role]) => {
      roleMap.set(roleId, role);
    });
    return roleMap;
  }

  /**
   * 按用户的最高等级角色进行分组
   */
  private groupMembersByHighestRole(
    memberIds: string[],
    memberRolesRecord: Record<string, string[]>,
    roleMap: Map<string, Role>
  ): Map<string, string[]> {
    const memberGroups = new Map<string, string[]>();

    // 使用 server 返回的 memberIds 保证成员顺序稳定
    for (const userId of memberIds) {
      const roleIds = memberRolesRecord[userId];
      if (!roleIds || roleIds.length === 0) continue;
      console.log("roleIds",roleIds)

      const highestRole = this.findHighestRole(roleIds, roleMap);
      if (!highestRole) continue;
      console.log("name",highestRole.name,"level",highestRole.level)
      this.addUserToGroup(memberGroups, highestRole.name, userId);
    }

    return memberGroups;
  }

  /**
   * 找到用户的最高等级角色
   */
  private findHighestRole(roleIds: string[], roleMap: Map<string, Role>): Role | null {
    let highest: Role | null = null;

    for (const roleId of roleIds) {
      const role = roleMap.get(roleId);
      if (!role) continue;

      if (!highest) {
        highest = role;
        continue;
      }

      // level 数值越大优先级越高
      if ((role.level ?? 0) > (highest.level ?? 0)) {
        highest = role;
      }
    }

    return highest;
  }

  /**
   * 将用户添加到对应的角色分组中
   */
  private addUserToGroup(
    memberGroups: Map<string, string[]>,
    roleName: string,
    userId: string
  ): void {
    if (!memberGroups.has(roleName)) {
      memberGroups.set(roleName, []);
    }

    memberGroups.get(roleName)!.push(userId);
  }

  /**
   * 将Map格式转换为模板可用的数组格式，并按角色优先级排序
   */
  private convertToTemplateFormat(memberGroups: Map<string, string[]>, roleMap: Map<string, Role>): MemberGroup[] {
    // 先获取所有角色并按 level 排序，确保稳定的排序基础
    const sortedRoles = Array.from(roleMap.values())
      .sort((a, b) => {
        const levelA = a.level ?? 0;
        const levelB = b.level ?? 0;
        // level 数值越大排前面
        if (levelA !== levelB) {
          return levelB - levelA;
        }
        // 如果 level 相同，按名称排序保证稳定性
        return a.name.localeCompare(b.name);
      });

    // 按排序后的角色顺序构建结果数组
    const result: MemberGroup[] = [];

    for (const role of sortedRoles) {
      const userIds = memberGroups.get(role.name);
      if (userIds && userIds.length > 0) {
        result.push({
          roleName: role.name,
          userIds: userIds.slice() // 复制数组
        });
      }
    }

    return result;
  }

  ngOnDestroy() {
    this.subscriptions.forEach(subscription => subscription.unsubscribe());
  }
}

// src/components/MemberList.vue
<template>
  <div v-if="membersByRole.length" class="member-list">
    <div v-for="role in membersByRole" :key="role.roleName" class="role-section">
      <div class="role-header">
        <p>{{ role.roleName }}</p>
      </div>
      <div class="member-items">
        <div v-for="userId in role.userIds" :key="userId" class="member-item">
          <Avatar class="avatar" :id="userId" type="user" />
          <span class="member-name">{{ userStore.userInfoIndexById[userId]?.data?.nickname || userId }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onBeforeUnmount, onMounted, ref } from 'vue';
import { Subscription } from 'rxjs';
import Avatar from './Avatar.vue';
import { serverStore, userStore } from '@/services/state';
import { serverService, type Role } from '@/services/api/server';
import { requestService } from '@/services/request';

interface MemberGroup {
  roleName: string;
  userIds: string[];
}

const membersByRole = ref<MemberGroup[]>([]);
const subscriptions: Subscription[] = [];

const loadAndGroupMembers = (data: {
  memberIds: string[];
  memberRolesRecord: Record<string, string[]>;
  rolesRecord: Record<string, Role>;
}) => {
  requestService.getUserInfo(data.memberIds).then();

  const roleMap = createRoleMap(data.rolesRecord);
  const memberGroups = groupMembersByHighestRole(data.memberIds, data.memberRolesRecord, roleMap);
  membersByRole.value = convertToTemplateFormat(memberGroups, roleMap);
};

const createRoleMap = (rolesRecord: Record<string, Role>): Map<string, Role> => {
  const roleMap = new Map<string, Role>();
  Object.entries(rolesRecord).forEach(([roleId, role]) => {
    roleMap.set(roleId, role);
  });
  return roleMap;
};

const groupMembersByHighestRole = (
  memberIds: string[],
  memberRolesRecord: Record<string, string[]>,
  roleMap: Map<string, Role>
): Map<string, string[]> => {
  const memberGroups = new Map<string, string[]>();
  for (const userId of memberIds) {
    const roleIds = memberRolesRecord[userId];
    if (!roleIds || roleIds.length === 0) continue;
    const highestRole = findHighestRole(roleIds, roleMap);
    if (!highestRole) continue;
    addUserToGroup(memberGroups, highestRole.name, userId);
  }
  return memberGroups;
};

const findHighestRole = (roleIds: string[], roleMap: Map<string, Role>): Role | null => {
  let highest: Role | null = null;
  for (const roleId of roleIds) {
    const role = roleMap.get(roleId);
    if (!role) continue;
    if (!highest) {
      highest = role;
      continue;
    }
    if ((role.level ?? 0) > (highest.level ?? 0)) {
      highest = role;
    }
  }
  return highest;
};

const addUserToGroup = (memberGroups: Map<string, string[]>, roleName: string, userId: string) => {
  if (!memberGroups.has(roleName)) {
    memberGroups.set(roleName, []);
  }
  memberGroups.get(roleName)!.push(userId);
};

const convertToTemplateFormat = (memberGroups: Map<string, string[]>, roleMap: Map<string, Role>): MemberGroup[] => {
  const sortedRoles = Array.from(roleMap.values()).sort((a, b) => {
    const levelA = a.level ?? 0;
    const levelB = b.level ?? 0;
    if (levelA !== levelB) {
      return levelB - levelA;
    }
    return a.name.localeCompare(b.name);
  });

  const result: MemberGroup[] = [];
  for (const role of sortedRoles) {
    const userIds = memberGroups.get(role.name);
    if (userIds && userIds.length > 0) {
      result.push({
        roleName: role.name,
        userIds: userIds.slice(),
      });
    }
  }
  return result;
};

onMounted(() => {
  if (!serverStore.currentServer) {
    return;
  }
  const sub = serverService.memberData$.subscribe((data) => {
    if (data) {
      loadAndGroupMembers(data);
    }
  });
  subscriptions.push(sub);
});

onBeforeUnmount(() => {
  subscriptions.forEach((subscription) => subscription.unsubscribe());
});
</script>

<style scoped>
.member-list {
  flex: 0 0 auto;
  width: auto;
  min-width: 200px;
  max-width: 300px;
  overflow: auto;
  border-left: 0.1rem solid #acacac;
  background-color: white;
  color: #000000;
  padding-right: 10px;
  padding-left: 10px;
}

.role-section {
  margin-top: 15px;
}

.role-header {
  margin-bottom: 5px;
}

.member-items {
  display: flex;
  flex-direction: column;
}

.member-item {
  display: flex;
  align-items: center;
  margin-bottom: 5px;
  padding: 3px;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

.member-item:hover {
  border-radius: 5px;
  background-color: #b5b5b5;
}

.avatar {
  height: 32px;
  width: 32px;
  border-radius: 10px;
  margin-right: 10px;
}

.member-name {
  font-size: 16px;
  color: #3b96ff;
  font-weight: bold;
}
</style>
