// src/app/components/server-profile-setting/server-profile-setting.component.ts
import {Component, Input, OnInit, ViewChild} from '@angular/core';
import {ImageEditComponent} from "../image-edit/image-edit.component";
import {NgIf} from "@angular/common";
import {ServerService} from "../../services/api/server.service";
import {AvatarComponent} from "../avatar/avatar.component";
import {FormsModule} from "@angular/forms";
import {RequestService} from "../../services/request.service";
import {CommonDataService} from "../../services/common-data.service";

type serverInfo = {
  serverName: string | null;
  serverDescription: string | null;
};



@Component({
  selector: 'app-server-profile-setting',
  standalone: true,
  imports: [
    ImageEditComponent,
    NgIf,
    AvatarComponent,
    FormsModule
  ],
  templateUrl: './server-profile-setting.component.html',
  styleUrl: './server-profile-setting.component.css'
})
export class ServerProfileSettingComponent implements OnInit{
  @Input() serverId!: string; // 通过输入属性接收服务器 ID
  @ViewChild('serverIcon') serverIcon!: AvatarComponent;

  imageEditDialog = false;
  file!: File;
  cropped!: string;

  originServerInfo: serverInfo = {
    serverName: null,
    serverDescription: null
  };

  serverInfo: serverInfo = {
    serverName: null,
    serverDescription: null
  };

  constructor(protected serverService:ServerService,protected  request: RequestService,protected commonDataService:CommonDataService) {
  }

  async updateServerInfo() {
    const success = await this.serverService.updatesServerProfile(
      this.serverId,
      this.serverInfo.serverName,
      this.serverInfo.serverDescription
    );
    if (!success) return;

    await this.request.requestServerInfoByIds([this.serverId]); // 等待最新数据

    // 用 Object.assign 保留原对象引用，只更新字段
    Object.assign(
      this.serverService.serverInfo,
      this.commonDataService.getServerInfoById(this.serverId)
    );

    alert("成功更改");
  }


  async selectFile() {
    try {
      const [fileHandle] = await (window as any).showOpenFilePicker({
        types: [
          {
            description: 'Images',
            accept: {
              'image/*': ['.png', '.jpg', '.jpeg', '.gif']
            }
          }
        ],
        multiple: false
      });
      this.file = await fileHandle.getFile();
      this.toggleImageEditDialog();
    } catch (error) {
      console.error('文件选择已取消', error);
    }
  }
  onConfirm(cropped: any) {
    console.log('裁剪完成，结果是：', cropped);
    this.cropped = URL.createObjectURL(cropped);
    this.toggleImageEditDialog();
    this.serverService.uploadIcon(cropped,this.serverId).subscribe({
      next: () => {
        console.log('Upload successful');
        this.serverIcon.refreshAvatar();
      },
      error: err => console.error('Upload failed', err)
    })
  }

  toggleImageEditDialog() {
    this.imageEditDialog = !this.imageEditDialog;
  }

  ngOnInit(): void {
    this.originServerInfo.serverName = this.serverService.serverInfo.name
    this.originServerInfo.serverDescription = this.serverService.serverInfo.description
    this.serverInfo.serverName = this.serverService.serverInfo.name
    this.serverInfo.serverDescription = this.serverService.serverInfo.description
  }

  get hasChanges(): boolean {
    return this.originServerInfo.serverName !== this.serverInfo.serverName ||
      this.originServerInfo.serverDescription !== this.serverInfo.serverDescription;
  }

}

<app-avatar class="avatar" type="server" [id]="serverId" (click)="selectFile()"></app-avatar>

<div class="input-item">
  <label class="input-label">服务器名称</label>
  <input class="input">
</div>

<app-image-edit *ngIf="imageEditDialog" [file]="file" (close)="toggleImageEditDialog()" (confirm)="onConfirm($event)" ></app-image-edit>

// src/components/ServerProfileSetting.vue
<template>
  <Avatar ref="serverIconRef" class="avatar" type="server" :id="serverId" @click="selectFile" />

  <div class="input-item">
    <label class="input-label">服务器名称</label>
    <input v-model="serverInfo.serverName" class="input" />
  </div>

  <div class="input-item">
    <label class="input-label">服务器简介</label>
    <textarea v-model="serverInfo.serverDescription" class="input"></textarea>
  </div>

  <div>
    <button
      :class="hasChanges ? 'save-button' : 'save-button-disable'"
      :disabled="!hasChanges"
      @click="updateServerInfo"
    >
      保存
    </button>
  </div>

  <ImageEdit v-if="imageEditDialog && file" :file="file" @close="toggleImageEditDialog" @confirm="onConfirm" />
</template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue';
import Avatar from './Avatar.vue';
import ImageEdit from './ImageEdit.vue';
import { serverService } from '@/services/api/server';
import { requestService } from '@/services/request';
import { serverStore } from '@/services/state';

const props = defineProps<{
  serverId: string;
}>();

const serverIconRef = ref<InstanceType<typeof Avatar> | null>(null);

const imageEditDialog = ref(false);
const file = ref<File | null>(null);

const originServerInfo = ref({
  serverName: null as string | null,
  serverDescription: null as string | null,
});

const serverInfo = ref({
  serverName: null as string | null,
  serverDescription: null as string | null,
});

const updateServerInfo = async () => {
  const success = await serverService.updatesServerProfile(
    props.serverId,
    serverInfo.value.serverName,
    serverInfo.value.serverDescription
  );
  if (!success) return;

  await requestService.requestServerInfoByIds([props.serverId]);

  Object.assign(serverService.serverInfo, serverStore.getServerInfoById(props.serverId));
  alert('成功更改');
};

const selectFile = async () => {
  try {
    const [fileHandle] = await (window as any).showOpenFilePicker({
      types: [
        {
          description: 'Images',
          accept: {
            'image/*': ['.png', '.jpg', '.jpeg', '.gif'],
          },
        },
      ],
      multiple: false,
    });
    file.value = await fileHandle.getFile();
    toggleImageEditDialog();
  } catch (error) {
    console.error('文件选择已取消', error);
  }
};

const onConfirm = (croppedBlob: Blob) => {
  toggleImageEditDialog();
  serverService.uploadIcon(croppedBlob as File, props.serverId).subscribe({
    next: () => {
      serverIconRef.value?.refreshAvatar();
    },
    error: (err) => console.error('Upload failed', err),
  });
};

const toggleImageEditDialog = () => {
  imageEditDialog.value = !imageEditDialog.value;
};

onMounted(() => {
  originServerInfo.value.serverName = serverService.serverInfo?.name ?? null;
  originServerInfo.value.serverDescription = serverService.serverInfo?.description ?? null;
  serverInfo.value.serverName = serverService.serverInfo?.name ?? null;
  serverInfo.value.serverDescription = serverService.serverInfo?.description ?? null;
});

const hasChanges = computed(() => {
  return (
    originServerInfo.value.serverName !== serverInfo.value.serverName ||
    originServerInfo.value.serverDescription !== serverInfo.value.serverDescription
  );
});
</script>

<style scoped>
.avatar {
  width: 128px;
  height: 128px;
  border-radius: 10px;
  margin-top: 12px;
  margin-bottom: 12px;
  object-fit: cover;
  display: block;
}

.input-item {
  display: flex;
  flex-direction: column;
  margin-bottom: 15px;
}

.input-item:last-child {
  margin-bottom: 0;
}

.input-label {
  font-size: 14px;
  margin-bottom: 4px;
  text-align: left;
}

.input {
  padding: 8px 12px;
  border: 1px solid #ccc;
  border-radius: 6px;
  outline: none;
  resize: none;
}

.save-button {
  margin-top: 1.2rem;
  width: 150px;
  height: 40px;
  border-radius: 25px;
  background: #057feb;
  border: none;
  color: white;
  transition: background 0.3s ease, transform 0.5s ease;
}

.save-button-disable {
  margin-top: 1.2rem;
  width: 150px;
  height: 40px;
  border-radius: 25px;
  background: #878787;
  border: none;
  color: white;
  transition: background 0.3s ease, transform 0.5s ease;
}

.save-button:hover {
  transform: scale(1.05);
}
</style>
