// src/components/ServerSettingDialog.vue
<template>
  <div class="modal-overlay">
    <div class="modal-content">
      <button class="icon-close-btn" aria-label="关闭" @click="onClose">&times;</button>
      <div class="main-container">
        <div class="sidebar">
          <div
            v-for="(item, i) in sidebarItems"
            :key="i"
            :class="{ selected: selectedIndex === i }"
            @click="selectItem(i)"
          >
            <span>{{ item.label }}</span>
          </div>
        </div>
        <div class="context">
          <ServerProfileSetting :serverId="serverId" />
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, ref } from 'vue';
import { useRouter } from 'vue-router';
import ServerProfileSetting from './ServerProfileSetting.vue';
import { serverService } from '@/services/api/server';
import { serverStore } from '@/services/state';

const props = defineProps<{
  serverId: string;
}>();

const emit = defineEmits<{
  (e: 'close'): void;
}>();

const router = useRouter();
const selectedIndex = ref(0);
const sidebarItems = ref<Array<{ label: string; action?: () => void; button?: boolean }>>([]);

onMounted(() => {
  sidebarItems.value = [{ label: '服务器资料' }];
  if (serverService.currentRolePermissions.includes(0)) {
    sidebarItems.value.push({
      label: '解散服务器',
      action: () => dissolveServer(),
      button: true,
    });
  }
});

const selectItem = (index: number) => {
  const item = sidebarItems.value[index];
  if (!item.button) {
    selectedIndex.value = index;
  }
  if (item.action) {
    item.action();
  }
};

const onClose = () => {
  emit('close');
};

const dissolveServer = () => {
  if (!confirm('确认要解散该服务器吗？')) {
    return;
  }
  serverService.deleteServer(props.serverId).then(() => {
    serverStore.servers = serverStore.servers.filter((item) => item !== props.serverId);
    serverStore.currentServer = '';
    router.push('/main/session');
    emit('close');
  });
};
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  top: 0;
  left: 0;
  width: 100vw;
  height: 100vh;
  background-color: var(--color-bg-overlay);
  display: flex;
  justify-content: center;
  align-items: center;
  z-index: 1000;
}

.modal-content {
  position: relative;
  display: flex;
  flex-direction: column;
  align-items: center;
  background: var(--color-bg-panel);
  border-radius: 12px;
  padding: 24px 24px 16px;
  width: 400px;
  max-height: 80vh;
  overflow-y: auto;
  box-shadow: var(--shadow-lg);
  text-align: center;
  color: var(--color-text-primary);
}

.main-container {
  width: 100%;
  display: flex;
  flex-direction: row;
}

.icon-close-btn {
  position: absolute;
  top: 16px;
  right: 16px;
  background: transparent;
  border: none;
  font-size: 24px;
  color: var(--color-text-muted);
  cursor: pointer;
  transition: color 0.2s ease;
}

.icon-close-btn:hover {
  color: var(--color-text-primary);
}

.sidebar {
  color: var(--color-text-primary);
  display: flex;
  flex-direction: column;
  margin-right: 50px;
}

.sidebar div {
  display: flex;
  align-items: center;
  margin-bottom: 15px;
  padding: 10px;
  border-radius: 8px;
  transition: background-color 0.3s;
  cursor: pointer;
}

.sidebar div:hover {
  background-color: var(--color-bg-panel-subtle);
}

.sidebar div.selected {
  background-color: var(--color-border-default);
  font-weight: bold;
}

.sidebar img {
  width: 24px;
  height: 24px;
  margin-right: 10px;
}

.sidebar span {
  font-size: 16px;
  font-weight: 500;
  margin-right: 10px;
}

.context {
}
</style>

// src/app/components/server-setting-dialog/server-setting-dialog.component.ts
import {Component, EventEmitter, Input, OnInit, Output} from '@angular/core';
import {FormsModule} from "@angular/forms";
import {ImageEditComponent} from "../image-edit/image-edit.component";
import {NgClass, NgForOf, NgIf} from "@angular/common";
import {Router} from "@angular/router";
import {ServerProfileSettingComponent} from "../server-profile-setting/server-profile-setting.component";
import {ServerService} from "../../services/api/server.service";
import {CommonDataService} from "../../services/common-data.service";

@Component({
  selector: 'app-server-setting-dialog',
  standalone: true,
  imports: [
    FormsModule,
    ImageEditComponent,
    NgIf,
    NgForOf,
    NgClass,
    ServerProfileSettingComponent
  ],
  templateUrl: './server-setting-dialog.component.html',
  styleUrl: './server-setting-dialog.component.css'
})
export class ServerSettingDialogComponent implements OnInit{
  @Input() serverId!: string; // 通过输入属性接收服务器 ID
  selectedIndex: number = 0; // 默认没有选中按钮

  sidebarItems: { label: string, action?: () => void, button?: boolean }[] = [];

  ngOnInit(): void {

    this.sidebarItems = [
      { label: '服务器资料' },
      // { label: '身分组' },
      // { label: '成员管理' },
      // { label: '安全设置' }
    ];


    if (this.serverServer.currentRolePermissions.includes(0)) {
      this.sidebarItems.push({
        label: '解散服务器',
        action: () => this.dissolveServer(),
        button: true
      });
    }
  }

  constructor(private router: Router,private serverServer:ServerService,private commonDataService:CommonDataService) {

  }

  selectItem(index: number): void {
    const item = this.sidebarItems[index];
    if (!item.button){
      this.selectedIndex = index;
    }
    if (item.action) {
      item.action();
    }
  }

  @Output() close = new EventEmitter<void>(); // ← 添加关闭事件

  onClose() {
    this.close.emit(); // ← 发出关闭事件
  }

  dissolveServer() {
    if (!confirm("确认要解散该服务器吗？")) {
      return;
    }
    this.serverServer.deleteServer(this.serverId).then(v => {
      this.commonDataService.servers = this.commonDataService.servers.filter(item => item != this.serverId);
      this.commonDataService.currentServer = "";
      this.router.navigate(['/main/session']).then();
      this.close.emit();
    });
  }



}

<div class="modal-overlay">
  <div class="modal-content">
    <button class="icon-close-btn" aria-label="关闭" (click)="onClose()">&times;</button>
    <div class="main-container">
      <div class="sidebar">
        <div
          *ngFor="let item of sidebarItems; let i = index"
          [ngClass]="{'selected': selectedIndex === i}"
          (click)="selectItem(i)">
          <span>{{ item.label }}</span>
        </div>
      </div>
      <div class="context">
        <app-server-profile-setting [serverId]="serverId"/>
      </div>
    </div>
  </div>
</div>
